### PR TITLE
Add i18n

### PR DESCRIPTION
**Pull request by DRSchlaubi**
- Add nuxt-i18n
- Add default language files

### CODE REVIEW

**Comment by DRSchlaubi** [comment]
@Rxsto is supposed to add that he's the REAL frontend guy I am more the frontend  skid

**Comment by Rxsto** [comment]
Added language picker to navbar ✔

**Comment by Rxsto** [comment]
@DRSchlaubi when using the routes the language is constantly changing back to the default locale, might wanna look into that.

**Comment by DRSchlaubi** [comment]
just don't expect it to be fixed before 2080

**Comment by DRSchlaubi** [comment]
Wow that was easy

**Pull request merged**
